services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: u_gourmestre
      POSTGRES_PASSWORD: tongue
      POSTGRES_DB: Gourmestre
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:

